[package]
name = "rust_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.13"
prost = "0.13.5"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
tonic-build = "0.13"
