name: Cargo Audit

on:
  push:
    paths:
      - '.github/workflows/cargo-audit.yaml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    paths:
      - '.github/workflows/cargo-audit.yaml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/audit@v1
        name: Audit Rust Dependencies
